In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
import time 
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print( "Vectorized version: " + str(1000*(toc-tic)) + "ms" )

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print( "For loop: " + str(1000*(toc-tic)) + "ms" )

249616.61173261818
Vectorized version: 9.516716003417969ms
249616.61173262206
For loop: 473.0658531188965ms


In [3]:
v = np.random.rand(1000000)
u = np.exp(v)
print(u)

[1.97201401 2.67969494 1.62199267 ... 1.79501129 1.16549831 2.30224689]


In [4]:
v = np.random.rand(1000000) 
u = np.log(v)
print(u)

[-1.17710866 -0.65852613 -0.79249871 ... -3.95717572 -0.21377321
 -0.39341035]


In [5]:
v = np.random.rand(1000000)
u = np.abs(v)
print(u)

[0.08292222 0.82232433 0.06288948 ... 0.19477491 0.65726543 0.43217993]


In [6]:
v = np.random.rand(1000000)
u = np.maximum(v, 0)
print(u)

[0.18846662 0.19605985 0.43976212 ... 0.82788084 0.70416488 0.91042024]


In [7]:
v = np.random.rand(1000000)
u = np.minimum(v, 0)
print(u)

[0. 0. 0. ... 0. 0. 0.]


In [8]:
v = np.random.rand(1000000)
u = np.tanh(v)
print(u)

[0.40365167 0.07978558 0.74076459 ... 0.08058464 0.45746064 0.49504148]


In [9]:
A = np.array([[56.0, 0.0, 4.4, 68.0], 
              [1.2, 104.0, 52.0, 8.0], 
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [10]:
cal = A.sum(axis=0)

In [11]:
print(cal)

[ 59.  239.  155.4  76.9]


In [12]:
percentage = 100*A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [13]:
percentage = 100*A/cal

In [14]:
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [15]:
nums = np.array([1, 2, 3, 4]) 
nums = (nums + 100).reshape(4, 1)
print(nums)

[[101]
 [102]
 [103]
 [104]]


In [16]:
a = np.random.rand(5)
print(a)

[0.79339082 0.01009099 0.56329676 0.91938711 0.33837304]


In [17]:
print(a.shape)

(5,)


In [18]:
print(a.T)

[0.79339082 0.01009099 0.56329676 0.91938711 0.33837304]


In [19]:
print(np.dot(a, a.T))

1.9066430282434763


In [20]:
a = np.random.rand(5, 1)

In [21]:
print(a)

[[0.37658994]
 [0.76008744]
 [0.02202373]
 [0.7488483 ]
 [0.82854629]]


In [22]:
print(a.T)

[[0.37658994 0.76008744 0.02202373 0.7488483  0.82854629]]


In [23]:
print(np.dot(a, a.T))

[[1.41819980e-01 2.86241282e-01 8.29391604e-03 2.82008735e-01
  3.12022194e-01]
 [2.86241282e-01 5.77732922e-01 1.67399626e-02 5.69190193e-01
  6.29767630e-01]
 [8.29391604e-03 1.67399626e-02 4.85044794e-04 1.64924347e-02
  1.82476818e-02]
 [2.82008735e-01 5.69190193e-01 1.64924347e-02 5.60773782e-01
  6.20455482e-01]
 [3.12022194e-01 6.29767630e-01 1.82476818e-02 6.20455482e-01
  6.86488950e-01]]


In [25]:
x=np.array([[[1],[2]],[[3],[4]]])
print(x.shape)

(2, 2, 1)


In [26]:
print(x)

[[[1]
  [2]]

 [[3]
  [4]]]


In [27]:
a = np.random.rand(3, 3)
b = np.random.rand(2, 1)
c = a+b
print(c)

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [29]:
a = np.random.rand(4, 3)
b = np.random.rand(3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [30]:
a=np.random.randn(12288,150) 
b=np.random.randn(150,45)
c=np.dot(a,b)
print(c.shape)

(12288, 45)


In [34]:
a = np.array([[1, 2, 9, 5], [3, 4, 8, 7], [5, 6, 7, 2]])
b = np.array([[10],[10], [10]])
c = np.zeros((3, 4))
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[i]
print(c)

[[11. 12. 19. 15.]
 [13. 14. 18. 17.]
 [15. 16. 17. 12.]]


C:\Users\Abdul\AppData\Local\Temp\ipykernel_5956\3450440494.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  c[i][j] = a[i][j] + b[i]


In [38]:
c = a + b
print(c)

[[11 12 19 15]
 [13 14 18 17]
 [15 16 17 12]]


In [39]:
a = np.random.rand(3, 3)
b = np.random.rand(3, 3)
c = a**2+ b.T **2

print(c)

[[0.68939783 1.4763909  0.30796628]
 [0.80434052 0.67421164 1.07011996]
 [0.56471211 1.2931827  0.64921142]]
